services:
  securecheckplus_db:
    image: postgres
    restart: always
    container_name: securecheckplus_db
    env_file: "./backend/.env"
    ports:
      - "5432:5432"

  smtp_mailserver:
    image: maildev/maildev
    container_name: mailserver
    ports:
      - "1080:80"

  ldap_server:
    image: "osixia/openldap:1.5.0"
    command: "--copy-service --loglevel debug"
    env_file: "./backend/.env"
    ports:
      - "390:389"
    volumes:
      - ./assets/ldap/bootstrap:/container/service/slapd/assets/config/bootstrap/ldif/custom

