# Generated by Django 4.0.3 on 2023-04-06 12:07

from django.db import migrations, models
import django.db.models.deletion

from utilities import constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=255, unique=True)),
                ('base_severity', models.CharField(default='NA', max_length=255)),
                ('cvss', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('epss', models.FloatField(default=0, null=True)),
                ('published', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('description', models.TextField(blank=True)),
                ('attack_vector', models.CharField(blank=True, choices=[('N', 'Network'), ('A', 'Adjacent'), ('L', 'Local'), ('P', 'Physical')], max_length=255)),
                ('attack_complexity', models.CharField(blank=True, choices=[('L', 'Low'), ('H', 'High')], max_length=255)),
                ('privileges_required', models.CharField(blank=True, choices=[('N', 'None'), ('L', 'Low'), ('H', 'High')], max_length=255)),
                ('user_interaction', models.CharField(blank=True, choices=[('N', 'None'), ('R', 'Required')], max_length=255)),
                ('confidentiality_impact', models.CharField(blank=True, choices=[('H', 'High'), ('L', 'Low'), ('N', 'None')], max_length=255)),
                ('integrity_impact', models.CharField(blank=True, choices=[('H', 'High'), ('L', 'Low'), ('N', 'None')], max_length=255)),
                ('availability_impact', models.CharField(blank=True, choices=[('H', 'High'), ('L', 'Low'), ('N', 'None')], max_length=255)),
                ('scope', models.CharField(blank=True, choices=[('U', 'Unchanged'), ('C', 'Changed')], max_length=255)),
                ('recommended_url', models.CharField(blank=True, max_length=2048)),
            ],
            options={
                'db_table': 'securecheckplus_cve_object',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_name', models.CharField(max_length=255)),
                ('version', models.CharField(default='NA', max_length=255)),
                ('package_manager', models.CharField(max_length=255)),
                ('license', models.CharField(default='NA', max_length=255)),
                ('path', models.CharField(default='NA', max_length=2048)),
                ('in_use', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'securecheckplus_dependency',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=25, unique=True)),
                ('project_name', models.CharField(blank=True, max_length=25)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deployment_threshold', models.CharField(choices=[(6, 'Always'), (5, 'Critical'), (4, 'High'), (3, 'Medium'), (2, 'Low'), (1, 'None'), (0, 'Never')], default='MEDIUM', max_length=20)),
                ('api_key_hash', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'securecheckplus_project',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('T', 'Threat'), ('TWIP', 'Threat - Fix is WIP'), ('NT', 'No Threat'), ('TF', 'Threat fixed'), ('R', 'Review'), ('RA', 'Review again')], default='REVIEW', max_length=255)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('solution', models.CharField(choices=[('No solution needed', 'No Solution Needed'), ('Change version', 'Change Version'), ('Change dependency', 'Change Dependency'), ('Programming required', 'Programming'), ('No solution available', 'No Solution')], default='NO_SOLUTION_NEEDED', max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('cve_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.cveobject')),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.dependency')),
                ('score_metric_data', models.TextField(default=constants.DEFAULT_SCORE_METRIC_DATA)),
                ('overall_cvss_score', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('overall_cvss_severity', models.CharField(max_length=255, default=None, null=True)),
            ],
            options={
                'db_table': 'securecheckplus_report',
            },
        ),
    ]
