# Generated by Django 4.0.3 on 2023-04-06 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analyzer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dependency',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.project'),
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('dependency', 'cve_object')},
        ),
        migrations.AlterUniqueTogether(
            name='dependency',
            unique_together={('dependency_name', 'version', 'project')},
        ),
    ]
