# Generated by Django 5.1.2 on 2025-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='package_manager',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='overall_cvss_severity',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
