# Generated by Django 5.1.2 on 2025-03-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0003_project_auto_update_alter_dependency_package_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPEObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpe_id', models.CharField(max_length=255, unique=True)),
                ('dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.dependency')),
            ],
            options={
                'db_table': 'securecheckplus_cpe_object',
            },
        ),
    ]
